import type { Heading } from "@/lib/posts"
import { cn } from "@/lib/utils"

interface PostTocProps {
  headings: Heading[]
  wordCount: number
  readingTime: string
}

/**
 * PostToc — "On this page" left-rail outline.
 * Server component rendering anchor links to heading IDs.
 * The IDs here are generated by extractHeadings (via slugify),
 * which exactly matches the IDs set on h2/h3 in mdx-content.tsx.
 */
export function PostToc({ headings, wordCount, readingTime }: PostTocProps) {
  return (
    <aside className="hidden md:block bg-term-bg border-r border-term-rule px-6 py-10 text-[13px] text-term-fg-soft">
      {/* Label */}
      <div className="font-mono text-[11px] text-term-fg-muted tracking-[0.08em] uppercase mb-[18px]">
        On this page
      </div>

      {/* Heading list */}
      <nav>
        {headings.map((heading, i) => (
          <a
            key={heading.id}
            href={`#${heading.id}`}
            className={cn(
              "block py-[10px] font-sans text-[14px] leading-[1.35] transition-colors",
              heading.level === 3
                ? "pl-[30px] border-l border-term-rule text-term-fg-soft hover:text-term-fg"
                : "pl-[14px] border-l border-term-rule text-term-fg-soft hover:text-term-fg",
            )}
          >
            <span className="font-mono text-[11px] text-term-fg-muted mr-[10px]">
              {String(i + 1).padStart(2, "0")}
            </span>
            {heading.text}
          </a>
        ))}
      </nav>

      {/* Footer stats */}
      <div className="mt-8 pt-4 border-t border-term-rule font-mono text-[11px] text-term-fg-muted leading-[1.7]">
        <div>{wordCount.toLocaleString()} words</div>
        <div>~{readingTime} read</div>
      </div>
    </aside>
  )
}
